# Generated by Django 5.0.3 on 2024-03-05 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TNK', 'Танк'), ('HL', 'Хил'), ('DD', 'ДД'), ('MRCHNT', 'Торговец'), ('GLDMSTR', 'Гильдмастер'), ('QSTGVR', 'Квестгивер'), ('BLCKSMTH', 'Кузнец'), ('TNNR', 'Кожевник'), ('PTNMSTR', 'Зельевар'), ('WZRD', 'Мастер заклинаний')], default='DD', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fun_site.category')),
                ('percon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='***', max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fun_site.person')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_fix', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fun_site.person')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fun_site.post')),
            ],
        ),
    ]
