# Generated by Django 5.0.3 on 2024-03-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='percon',
            new_name='person',
        ),
    ]
