# Generated by Django 5.0.3 on 2024-03-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_site', '0003_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fun_site.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('TNK', 'Танки'), ('HL', 'Хили'), ('DD', 'ДД'), ('MRCHNT', 'Торговцы'), ('GLDMSTR', 'Гильдмастеры'), ('QSTGVR', 'Квестгиверы'), ('BLCKSMTH', 'Кузнецы'), ('TNNR', 'Кожевники'), ('PTNMSTR', 'Зельевары'), ('WZRD', 'Мастера заклинаний')], default='DD', max_length=8),
        ),
    ]
