# Generated by Django 5.0.3 on 2024-03-10 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_site', '0004_remove_person_category_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('TNK', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД'), ('MRCHNT', 'Торговцы'), ('GLDMSTR', 'Гильдмастеры'), ('QSTGVR', 'Квестгиверы'), ('BLCKSMTH', 'Кузнецы'), ('TNNR', 'Кожевники'), ('PTNMSTR', 'Зельевары'), ('WZRD', 'Мастера заклинаний')], default='DD', max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fun_site.category'),
            preserve_default=False,
        ),
    ]
