# Generated by Django 5.0.3 on 2024-03-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_site', '0006_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_fix',
            field=models.BooleanField(default=False),
        ),
    ]
